"""initial

Revision ID: 06316f606b65
Revises: 
Create Date: 2026-06-30 23:28:55.168291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06316f606b65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_cnj', sa.String(length=25), nullable=False),
    sa.Column('tribunal_alias', sa.String(length=50), nullable=False),
    sa.Column('apelido', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ultima_consulta_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processos_numero_cnj'), 'processos', ['numero_cnj'], unique=True)
    op.create_table('consultas_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('processo_id', sa.UUID(), nullable=True),
    sa.Column('executado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('movimentacoes_novas', sa.Integer(), nullable=True),
    sa.Column('erro_detalhe', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('processo_id', sa.UUID(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('codigo_movimento', sa.Integer(), nullable=True),
    sa.Column('nome_movimento', sa.String(), nullable=False),
    sa.Column('hash_dedup', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('capturado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processo_id', 'hash_dedup', name='uq_processo_hash_dedup')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacoes')
    op.drop_table('consultas_log')
    op.drop_index(op.f('ix_processos_numero_cnj'), table_name='processos')
    op.drop_table('processos')
    # ### end Alembic commands ###